/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_babeefone_VoiceActivityDetector */

#ifndef _Included_com_babeefone_VoiceActivityDetector
#define _Included_com_babeefone_VoiceActivityDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_babeefone_VoiceActivityDetector
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_babeefone_VoiceActivityDetector_init
  (JNIEnv *, jclass);

/*
 * Class:     com_babeefone_VoiceActivityDetector
 * Method:    process
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_com_babeefone_VoiceActivityDetector_process
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_babeefone_VoiceActivityDetector
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_babeefone_VoiceActivityDetector_free
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
